baseURL = "https://ayushved78.github.io/"
languageCode = "en-us"
title = "Ayush's Blog"
theme = "FixIt"
buildFuture = true
googleAnalytics = "G-75WGKEDCDW"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[params]
  title = "Hi, I'm Ayush 👋"
  description = "Welcome to my digital garden — thoughts, code, and experiments."
  defaultTheme = "dark" # dark by default
  disableThemeToggle = true # Don't allow users to switch light/dark
  enableReadingTime = true
  enableShare = true
  enableComment = true
  enableToc = true
  enablePostNav = true
  enableBreadcrumb = true
  ShowCodeCopyButtons = true
  disableScrollToTop = true

  mainSections = ["blog", "essay", "shelf"]
  archiveSection = ["blog", "essay", "shelf"]

  [params.search]
    enable = true
    placeholder = "Search..."

  [params.cover]
    linkFullImages = true
    image = "images/cover.jpeg"

  [params.home]
    rss = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# Social links for FixIt
[social]
  github = "https://github.com/ayushved78"
  linkedin = "https://www.linkedin.com/in/ayushsingh78/"
  twitter = "https://x.com/ayush_singh78"
  email = "mailto:ayush.ved78@gmail.com"
  kaggle = "https://www.kaggle.com/ayushuh"

# Menu
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 3

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/blog/"
  weight = 4

[[menu.main]]
  identifier = "misc"
  name = "Misc"
  url = "/essay/"
  weight = 5

[[menu.main]]
  identifier = "shelf"
  name = "Shelf"
  url = "/shelf/"
  weight = 6

# Markup and Syntax Highlighting
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  noClasses = false
